<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "empresas".
 *
 * @property integer $id
 * @property string $rfc
 * @property string $nombre
 * @property string $telefono
 * @property string $correo
 * @property string $encargado
 * @property string $domicilio
 *
 * @property Empleos[] $empleos
 */
class Empresa extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'empresas';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['rfc', 'nombre', 'telefono', 'encargado', 'domicilio'], 'required', 'message' => 'campo requerido'],
            [['telefono'], 'string', 'max' => 10 ,'message' => 'longitud invalida'],
            [['telefono'], 'integer', 'message' => 'Solo se admiiten numeros'],
            [['rfc'], 'string', 'max' => 20],
            [['nombre', 'encargado'], 'string', 'max' => 100],
            [['correo'], 'string', 'max' => 75],
            [['correo'], 'email', 'message' => 'Ingresa un correo valido'],
            [['domicilio'], 'string', 'max' => 150],
            [['rfc'], 'unique', 'message' => 'Ya existe una empresa con este RFC'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'rfc' => 'RFC',
            'nombre' => 'Nombre',
            'telefono' => 'Telefono',
            'correo' => 'Correo',
            'encargado' => 'Encargado',
            'domicilio' => 'Domicilio',
        ];
    }

    public function fields()
    {

        return parent::fields(); // TODO: Change the autogenerated stub
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEmpleos()
    {
        return $this->hasMany(Empleos::className(), ['id_empresa' => 'id']);
    }

    public static function dropdown()
    {
        return static::find()
                    ->select(['nombre'])
                    ->indexBy('id')
                    ->column();
    }


}
